services:
 mysql:
   image: 'mysql:8.0'
   environment:
     - 'MYSQL_DATABASE=yeogigangwon'
     - 'MYSQL_ROOT_PASSWORD=sdsqkqh55'
   ports:
     - '3306:3306'
   volumes:
     - mysql_data:/var/lib/mysql

volumes:
  mysql_data: