services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=yeogigangwon'
      - 'MONGO_INITDB_ROOT_PASSWORD=sdsqkqh!'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'

  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./python-api:/app
    restart: unless-stopped