services:
  mysql:
    image: 'mysql:8.0'
    container_name: backend-mysql # 컨테이너 이름 지정
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - 'MYSQL_DATABASE=yeogigangwon'
      - 'MYSQL_ROOT_PASSWORD=sdsqkqh55'
      - 'MYSQL_USER=appuser'
      - 'MYSQL_PASSWORD=sdsqkqh'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    # DB가 준비될 때까지 기다리게 하는 Health Check 기능
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "appuser", "-p'sdsqkqh'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    container_name: backend-python-api
    ports:
      - '5000:5000'
    environment:
#      - YOLO_CONFIG_DIR=/app/ultralytics_config
      - YOLO_CONFIG_DIR=/root/.config/Ultralytics
    volumes:
      - ./python-api:/app
    restart: unless-stopped

  backend-app:
    build:
      context: .
    container_name: backend-app
    ports:
      - '8080:8080'
    # mysql 서비스가 healthy 상태가 된 후 실행되도록 변경
    depends_on:
      mysql:
        condition: service_healthy
      python-api:
        condition: service_started
    # .env 파일의 변수들을 컨테이너 환경 변수로 로드
    env_file:
      - ./.env
    # 환경 변수 추가 및 DB 정보 명시
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yeogigangwon?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=sdsqkqh
      - TZ=Asia/Seoul
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "apis-navi.kakao.com:203.248.252.2"

volumes:
  mysql_data: