name: Docker Hub Login Test

on:
  workflow_dispatch:   # Actions 탭에서 수동 실행 가능

jobs:
  test-docker-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Verify login
        run: docker info
